### ISSUE TITLE
Trying to use Import Meshroom, not working, throwing exception with JSONDecodeError

### ISSUE THREAD

**Issue by SiL3NC3** [tibicen/meshroom2blender#10]
Blender 2.91.0, Python 3.7.7
running on Windows 10

Addon: current Master

**ERROR:**

Python: Traceback (most recent call last):
  File "D:\BlenderPortable\Data\user_scripts\addons\meshroom2blender-master\__init__.py", line 236, in execute
    cameras_sfm, cloud, dense_obj, tex_obj = read_meshlab(filepath)
  File "D:\BlenderPortable\Data\user_scripts\addons\meshroom2blender-master\__init__.py", line 70, in read_meshlab
    data = json.load(open(filepath, 'r'))
  File "D:\BlenderPortable\App\Blender64\2.91\python\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "D:\BlenderPortable\App\Blender64\2.91\python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\BlenderPortable\App\Blender64\2.91\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\BlenderPortable\App\Blender64\2.91\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

location: <unknown location>:-1

**Comment by UsaidPro** [comment]
Were you importing the Meshroom .mg file? I had the same issue when trying to import the .obj and .mtl files until I realized I needed to import the Meshroom .mg file instead.
