### ISSUE TITLE
Exif related import error

### ISSUE THREAD

**Issue by pedr2o** [tibicen/meshroom2blender#11]
Error importing a meshroom project that uses images without any EXIF?

```
Python: Traceback (most recent call last):
  File "C:\Users\Antoi\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\meshroom2blender-master\__init__.py", line 238, in execute
    import_cameras(cameras_sfm, self.img_front)
  File "C:\Users\Antoi\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\meshroom2blender-master\__init__.py", line 111, in import_cameras
    focal_length = float(view['metadata']['Exif:FocalLength'])
KeyError: 'Exif:FocalLength'

location: <unknown location>:-1
```

**Comment by ellenkantola** [comment]
Same problem. Any solutions or workarounds for this?

**Comment by onham** [comment]
anyone found any workarounds for this yet?
